{{- range $key, $value := .Values.rbac.roles }}
{{- if $value.createRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if $value.scope.cluster }}
kind: ClusterRole
metadata:
  name: {{ .name }}
{{- else }}
kind: Role
metadata:
  name: {{ $value.name }}
  namespace: {{ $value.scope.namespace}}
{{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups:
{{- range $value.apiGroups }}
      - {{ . }}
{{- end }}
    resources:
{{- range $value.resources }}
      - {{ . }}
{{- end }}
{{- if (($value.resourceNames)) }}
    resourceNames:
{{- range $value.resourceNames }}
      - {{ . }}
{{- end }}
{{- end }}
    verbs:
{{- range $value.verbs }}
      - {{ . }}
{{- end }}
{{- end }}
{{- end }}
