global:
  pattern: ansible-edge-gitops
  secretLoader:
    disabled: false
  hub:
    provider: aws
  options:
    installPlanApproval: Automatic
    syncPolicy: Automatic
    useCSV: false
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
