---
global:
  pattern: ansible-edge-gitops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  hub:
    provider: aws
    storageClassName: gp2

main:
  clusterGroupName: hub
