kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.odf.storageClass.name }}
  annotations:
    description: Provides Object Bucket Claims (OBCs) using the RGW
provisioner: openshift-storage.ceph.rook.io/bucket
parameters:
  objectStoreName: {{ .Values.odf.storageClass.objectStoreName }}
  objectStoreNamespace: {{ .Values.odf.namespace }}
  region: {{ .Values.global.datacenter.region }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
