apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: job-wait-for-portworx
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
      - image: quay.io/hybridcloudpatterns/utility-container
        command:
        - /bin/bash
        - -x
        - -c
        - |
          stc_status=$(oc get stc -n {{ .Values.pxnamespace }} | grep -E "Online|Running" | wc -l)
          until [ "$stc_status" -eq "1" ];
          do
            echo "Portworx storagecluster not yet online"
            sleep 10
            stc_status=$(oc get stc -n {{ .Values.pxnamespace }} | grep -E "Online|Running" | wc -l)
          done
          echo "Portworx storagecluster online, waiting for all containers to start"
          num_px_pods=$(oc get pod -l name=portworx -n {{ .Values.pxnamespace }} --no-headers | wc -l)
          while [ 1 ];
          do
            num_px_pods_ready=$(oc get pod -l name=portworx -n {{ .Values.pxnamespace }} |grep -P '\s+([1-9]+[\d]*)\/\1\s+' | wc -l)
            if [ "$num_px_pods_ready" -eq "$num_px_pods" ]; then
              echo "Portworx is ready, $num_px_pods_ready of $num_px_pods pods running 2/2"
              exit 0
            fi
            echo "Portworx is not yet ready, $num_px_pods_ready of $num_px_pods pods running 2/2"
            sleep 15
          done
        name: wait-for-portworx-ready
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: portworx-sc-sa
      serviceAccountName: portworx-sc-sa
      terminationGracePeriodSeconds: 600
