#!/usr/bin/env ansible-playbook
---
- name: Parse secrets from local values secret file
  become: false
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    values_secret: "{{ lookup('env', 'HOME') }}/values-secret.yaml"
  tasks:
    - name: Parse "{{ values_secret }}"
      ansible.builtin.set_fact:
        secrets_values: "{{ lookup('file', values_secret) | from_yaml }}"

    - name: Set files fact
      ansible.builtin.set_fact:
        manifest_file_ref: "{{ secrets_values['files']['aap-manifest'] }}"

    - name: Set secrets for use in load controller playbook
      ansible.builtin.set_fact:
        secrets:
          kubeconfig: "{{ lookup('file', lookup('env', 'KUBECONFIG')) }}"
          manifest_file_ref: "{{ manifest_file_ref }}"
          rhsm:
            username: "{{ secrets_values['secrets']['rhsm']['username']  }}"
            password: "{{ secrets_values['secrets']['rhsm']['password']  }}"
          kiosk-extra:
            container_extra_params: "{{ secrets_values['secrets']['kiosk-extra']['container_extra_params'] }}"
          kiosk-ssh:
            username: "{{ secrets_values['secrets']['kiosk-ssh']['username'] }}"
            privatekey: "{{ secrets_values['secrets']['kiosk-ssh']['privatekey'] }}"
            publickey: "{{ secrets_values['secrets']['kiosk-ssh']['publickey'] }}"

    # - debug:
    #    var: secrets
